//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBX.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIENXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIENXE()
        {
            this.PHANCONGs = new HashSet<PHANCONG>();
            this.PHANCONGs1 = new HashSet<PHANCONG>();
            this.PHANCONGs2 = new HashSet<PHANCONG>();
            this.PHANCONGs3 = new HashSet<PHANCONG>();
        }
    
        public string IDNHANVIENXE { get; set; }
        public string HOTEN { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> NAMSINH { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string LOAIBANGLAI { get; set; }
        public Nullable<System.DateTime> NGAYTHAMGIA { get; set; }
        public string LOAINHANVIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs3 { get; set; }
    }
}
