//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBX.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONG
    {
        public string IDCHUYEN { get; set; }
        public string TAI1 { get; set; }
        public string TAI2 { get; set; }
        public string TAI3 { get; set; }
        public string TAI4 { get; set; }
    
        public virtual CHUYENXE CHUYENXE { get; set; }
        public virtual NHANVIENXE NHANVIENXE { get; set; }
        public virtual NHANVIENXE NHANVIENXE1 { get; set; }
        public virtual NHANVIENXE NHANVIENXE2 { get; set; }
        public virtual NHANVIENXE NHANVIENXE3 { get; set; }
    }
}
