//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBX.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUYENXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUYENXE()
        {
            this.CHUYENXEs = new HashSet<CHUYENXE>();
        }
    
        public string IDTUYEN { get; set; }
        public string BENDI { get; set; }
        public string BENDEN { get; set; }
        public Nullable<decimal> GIAVEMATDINH { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHATGIA { get; set; }
    
        public virtual BENXE BENXE { get; set; }
        public virtual BENXE BENXE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENXE> CHUYENXEs { get; set; }
    }
}
